syntax = "proto3";
package ET;
enum WorldStatusEnum
{
    WS_Init = 0;                                  // 初始化状态
    WS_Battle = 1;                                // 战斗状态
    WS_Finish = 2;                                // 战斗结束状态
}


//// 战斗世界通用数据结构
message BattleWorld
{
    uint32 Frame = 1;                           // 世界帧
    WorldStatusEnum WorldStatus = 2;            // 世界状态
    // TODO 世界的其他配置 天空盒 场景 等战场常规信息
}

message BattleUnitEntity
{
    int64 InsId = 1;                              // Unit 实例id
    repeated UnitEntityElemData EleDatas = 2;     // 数据项
}

message UnitEntityElemData
{
    ushort CompId = 1;                  // 组件id
    bytes ElemDatas = 2;                // element数据
}



////>>>>>>>>>>>>>>>>>> 常规信息 
// 常规信息
message UnitEntityCommonData // IUnitEntityElemData
{
    UETypeEnum UnitEntityType = 1;
    UELayerTypeEnum UELayerTypeEnum = 2;
    map<string, string> Datas = 3;
    int64 ConfigId = 4;                     // 配置ID
}

// 动画
message UnitEntityAnimation // IUnitEntityElemData
{
    AnimateStateEnum AnimateState = 1;    // 动画状态
}


// 位置
message UnitEntityPosition // IUnitEntityElemData
{
    Unity.Mathematics.float2 Position = 1;  // 位置
}


// 朝向角度
message UnitEntityTowardAngle // IUnitEntityElemData
{
    short TowardAngle = 1;                  // 朝向 -180-180
}



//// 玩家
// 玩家信息
message UnitEntityPlayerInfo // IUnitEntityElemData
{
    int64 PlayerId = 1;        // 玩家ID
    bool IsOnline = 2;         // 是否在线
    int64 LastLoginTime = 3;   // 上次登录时间
}

// 玩家数据
message UnitEntityCameraData // IUnitEntityElemData
{
    short CameraAngleOffSet = 1;            // 相机偏移角度
}

// 玩家技能
message UnitEntityPlayerSkill // IUnitEntityElemData
{
    repeated UnitEntityPlayerSkillDataItem SkillDataItems = 1;   // 技能数据
}

// 玩家技能DataItem
message UnitEntityPlayerSkillDataItem
{
    int64 SkillId = 1;
    SkillStatusEnum SkillStatusEnum = 2;    // 技能状态
    uint32 startFrame = 3;                  // 如果开始 技能当前的帧数是多少
}

//// 地块
// 地图信息
message UnitEntityMapMessage // IUnitEntityElemData
{
    int32 AreaSize = 1;                                     // 边宽度
    PlantInfo PlantInfo = 2;                                // 地块信息
}

message PlantInfo
{
    repeated CellInfo CellInfos = 2;                         // 网格
}


message CellInfo
{
    Unity.Mathematics.float2 CenterPoint = 1;
    repeated Unity.Mathematics.float4 Borders = 2;          // 边
}


// 地块辅助线信息
message GizmosPlantInfo // IUnitEntityElemData
{
    repeated Unity.Mathematics.float2 CenterPoints = 1;     // 点
    repeated Unity.Mathematics.float4 Borders = 2;          // 边
    int32 AreaSize = 3;                                     // 边宽度
}

// 玩家AOI辅助线
message GizmosPlayerAOICell // IUnitEntityElemData
{
    repeated int64 CellIds = 1;                             // Cell Ids
}

// 未登录的常规协议

//// 网络
// ResponseType G2C_Ping
message C2G_Ping // ISessionRequest
{
	int32 RpcId = 1;
}

message G2C_Ping // ISessionResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
	int64 Time = 4;
}

// ResponseType G2C_Benchmark
message C2G_Benchmark // ISessionRequest
{
	int32 RpcId = 1;
}

message G2C_Benchmark // ISessionResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}

//// 客户端Main向网络线程发送消息
// ResponseType NetBattle2MainLogin
message Main2NetBattleLogin // IRequest
{
	int32 RpcId = 1;
	int32 OwnerFiberId = 2;
	string RouterAddress = 3;				// 路由地址
	string Address = 3;						// 地址
	string Token = 4;						// Token 令牌	
}

message NetBattle2MainLogin // IResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}


// 3.玩家进入战斗 对Session 进行登录验证
// ResponseType B2C_Login
message C2B_Login // ISessionRequest
{
	int32 RpcId = 1;
	string Token = 2;
}

message B2C_Login // ISessionResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}

// 4.玩家通知准备完成
// ResponseType B2C_PlayerReadyCompleted
message C2B_PlayerReadyCompleted
{
	int32 RpcId = 1;
}

message B2C_PlayerReadyCompleted
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}

//// 通讯协议

// 1.获得玩家的视野世界信息
// ResponseType B2C_PlayerGetAllAOIWorldData
message C2B_PlayerGetAllAOIWorldData // IClientRequest
{
    int32 RpcId = 1;
}

message B2C_PlayerGetAllAOIWorldData // IClientResponse
{
    int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;

    BattleWorld BattleWorld = 4;
    repeated BattleUnitEntity AOIBattleUnitEntity = 5;
    repeated BattleUnitEntity BattleFieldUnitEntity = 6;    // 环境相关的UnitEntity 变化
    BattleUnitEntity MyPlayerUnitEntity = 7; // 我的UnitEntity
}

// 2.战斗场景玩家心跳
// ResponseType B2C_PlayerBattleWorldPing
message C2B_PlayerBattleWorldPing // IClientRequest
{
    int32 RpcId = 1;
    int64 ClientTime = 2;
}

message B2C_PlayerBattleWorldPing // IClientResponse
{
    int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
    int64 SendClientTime = 4;
    uint32 PlayerCurFrame = 4;         // 当前战斗世界的帧号
}

// 3.玩家战斗脏数据推送
message L2C_PlayerAOIWorldDirtyPush // IMessage
{
    uint32 LastSyncFrame = 1;                           // 开始帧数
    uint32 CurrentSyncFrame = 2;                        // 解锁帧数
    repeated BattleUnitEntity AddUnitEntiities = 3;     // 添加数据
    repeated BattleUnitEntity DirtyUnitEntities = 4;    // 脏数据
    repeated int64 DeleteUnitEntites = 5;               // 死亡数据
}


// 4.玩家操作脏数据
// ResponseType B2C_PlayerUploadDirtyElemData
message C2B_PlayerUploadDirtyElemData // IClientRequest
{
    int32 RpcId = 1;
    BattleUnitEntity BattleUnitEntity = 2; // 玩家用户UnitEntity 脏数据
}

message B2C_PlayerUploadDirtyElemData // IClientResponse
{
    int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}


// 5.玩家准备好进入战斗
message C2B_PlayeBattleReday // IClientRequest
{
    int32 RpcId = 1;
}

message B2C_PlayeBattleReday // IClientResponse
{
    int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}





//// 客户端Main向Lobby网络线程发送消息
// ResponseType NetLobby2MainLogin
message Main2NetLobbyLogin // IRequest
{
	int32 RpcId = 1;
	int32 OwnerFiberId = 2;
	string Account = 3;		// 账号
	string Password = 4; 	// 密码
}

message NetLobby2MainLogin // IResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;

	int64 PlayerId = 4;
}

// 登录账号服务器
// ResponseType A2C_Login
message C2A_Login // ISessionRequest
{
	int32 RpcId = 1;
	string  Account = 2;  // 帐号
	string  Password = 3;  // 密码
}

message A2C_Login // ISessionResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;

	string Address = 4;				// 大厅地址
	string Token = 5;				// Token
}

// 登录大厅服务器
// ResponseType L2C_LoginLobby
message C2L_LoginLobby // ISessionRequest
{
	int32 RpcId = 1;
	
	string Token = 2;				// Token
}

message L2C_LoginLobby // ISessionResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
	int64 PlayerId = 4;
}




// 链接服务器主动断开 (不要重连)
message G2C_SessionDisconnect // IMessage
{
    int32 Error = 1;    // 断开原因
}


message HttpGetRouterResponse
{
	repeated string Routers = 1;
	repeated string Accounts = 2;
}


// 玩家与大厅间的数据同步接口
// ============================= 数据结构 =============================
// 客户端服务器通用同步
message SyncDataUnitStruct
{
    uint32 Frame = 1;                                  // 编号
    repeated DataUnitBytes DataUnitBytes = 2;       // 数据单元
}

// 数据单元
message DataUnitBytes
{
    uint32 UnitId = 1;               // 单位uintId
    bytes UnitBytes = 2;            // 单位数据
}



// ============================= 协议 =============================
//// 数据同步
// 获得所有的 DataUnit 数据
// ResponseType L2C_GetAllDataUnits
message C2L_GetAllDataUnits // IClientRequest
{
    int32 RpcId = 1;
}

message L2C_GetAllDataUnits // IClientResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;

    SyncDataUnitStruct UnitStructData = 1;  // 数据
}

message L2C_SyncDirtyDataUnits // IMessage
{
    SyncDataUnitStruct UnitStructData = 1;  // 数据
}



// ============================= 数据 =============================
//// 玩家 角色信息
message RoleInfoUnitData // IUnitData
{
    string NickName = 1;    // 昵称
}

//// 战斗流程

// 1.开始匹配战斗
// ResponseType L2C_StartMatchBattle
message C2L_StartMatchBattle // IClientRequest
{
	int32 RpcId = 1;
	// TODO 各个战斗服的ping值
}

message L2C_StartMatchBattle // IClientResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}


// 2.通知匹配成功
message L2C_MatchBattleSuccess // IMessage
{
	string RouterAddress = 1;	// 路由地址
	string BattleAddress = 2;	// 战斗服地址
	string Token = 3;			// Token
}

// 1.开始世界进行
message C2B_DebugStartWorld // IClientRequest
{
    int32 RpcId = 1;
}

message B2C_DebugStartWorld // IClientResponse
{
    int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}

// 2.世界暂停
message C2B_DebugWorldPlush // IClientRequest
{
    int32 RpcId = 1;
}


message B2C_DebugWorldPlush // IClientResponse
{
    int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}


