
////>>>>>>>>>>>>>>>>>> 常规信息 
// 常规信息
message UnitEntityCommonData // IUnitEntityElemData
{
    UETypeEnum UnitEntityType = 1;
    UELayerTypeEnum UELayerTypeEnum = 2;
    map<string, string> Datas = 3;
    int64 ConfigId = 4;                     // 配置ID
}

// 动画状态
message UnitEntityAnimationStateData // IUnitEntityElemData
{
    AnimateStateEnum AnimateState = 1;    // 动画状态
    uint32 CurrentStateStartFrame = 2;    // 当前状态开始的逻辑帧
}


// 位置
message UnitEntityPosition // IUnitEntityElemData
{
    Unity.Mathematics.float2 Position = 1;  // 位置
}


// 朝向角度
message UnitEntityTowardAngle // IUnitEntityElemData
{
    short TowardAngle = 1;                  // 朝向 -180-180
}

