
////>>>>>>>>>>>>>>>>>> 常规信息 
// 常规信息
message UnitEntityCommonData // IUnitEntityElemData
{
    UETypeEnum UnitEntityType = 1;
    UELayerTypeEnum UELayerTypeEnum = 2;
    int64 ConfigId = 3;                                             // 配置ID
    map<UnitEntityNumericalTypeEnum, int64> NumericalDatas = 4;     // 数值
    map<UnitEntityStringTypeEnum, string> StringDatas = 5;          // 字符串配置
}

// 动画状态
message UnitEntityAnimationStateData // IUnitEntityElemData
{
    AnimateStateEnum AnimateState = 1;                              // 动画状态
    uint32 ActiveFrame = 2;                                         // 当前状态开始的逻辑帧
    UnitEntityAnimationSkillStateData CurrentSkillStateData = 3;    // 如果动画状态是技能状态,当前技能的信息
}

message UnitEntityAnimationSkillStateData
{
    int64 SkillId = 1;                      // 当前技能
    uint32 ActiveFrame = 2;                 // 技能如果开始 开始的逻辑帧
}


// 位置
message UnitEntityPosition // IUnitEntityElemData
{
    Unity.Mathematics.float2 Position = 1;  // 位置
}


// 朝向角度
message UnitEntityTowardAngle // IUnitEntityElemData
{
    short TowardAngle = 1;                  // 朝向 -180-180
}


// 技能项
message UnitEntitySkillData // IUnitEntityElemData
{
    map<int64, UnitEntitySkillDataItem> SkillId2UnitEntitySkillDataItems = 1;   // 技能数据
}

// 技能DataItem
message UnitEntitySkillDataItem
{
    int64 SkillId = 1;
    SkillStatusEnum SkillStatusEnum = 2;    // 技能状态
    uint32 ActiveFrame = 3;                 // 技能如果开始 开始的逻辑帧
    uint32 CDFrame = 4;                     // CD的Frame 帧数
}


// Buff数据
message UnitEntityBuffData // IUnitEntityElemData
{
    map<int64, UnitEntityBuffDataItem> BuffId2BuffDataItems = 4;     // 数值
}

// Buff DataItem
message UnitEntityBuffDataItem
{
    int64 BuffId = 1;                      // buffID
}



////////////////////////// 数值
// UnitEntity 血量数据
message UnitEntityBloodData // IUnitEntityElemData
{
    int64 CurrentBlood = 1;                 // 当前血量
}