//// 通讯协议

// 1.获得玩家的视野世界信息
// ResponseType B2C_PlayerGetAllAOIWorldData
message C2B_PlayerGetAllAOIWorldData // IClientRequest
{
    int32 RpcId = 1;
}

message B2C_PlayerGetAllAOIWorldData // IClientResponse
{
    int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;

    BattleWorld BattleWorld = 4;
    repeated BattleUnitEntity AOIBattleUnitEntity = 5;
    repeated BattleUnitEntity BattleFieldUnitEntity = 6;    // 环境相关的UnitEntity 变化
    BattleUnitEntity MyPlayerUnitEntity = 7;                // 我的UnitEntity
    int32 LogicInterval = 8;                                // 逻辑间隔
}

// 2.战斗场景玩家心跳
// ResponseType B2C_PlayerBattleWorldPing
message C2B_PlayerBattleWorldPing // IClientRequest
{
    int32 RpcId = 1;
    int64 ClientTime = 2;
}

message B2C_PlayerBattleWorldPing // IClientResponse
{
    int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
    int64 SendClientTime = 4;
    uint32 PlayerCurFrame = 4;         // 当前战斗世界的帧号
}

// 3.玩家战斗脏数据推送
message L2C_PlayerAOIWorldDirtyPush // IMessage
{
    uint32 LastSyncFrame = 1;                           // 开始帧数
    uint32 CurrentSyncFrame = 2;                        // 解锁帧数
    repeated BattleUnitEntity AddUnitEntiities = 3;     // 添加数据
    repeated BattleUnitEntity DirtyUnitEntities = 4;    // 脏数据
    repeated int64 DeleteUnitEntites = 5;               // 死亡数据
}


// 4.玩家操作脏数据
// ResponseType B2C_PlayerUploadDirtyElemData
message C2B_PlayerUploadDirtyElemData // IClientRequest
{
    int32 RpcId = 1;
    BattleUnitEntity BattleUnitEntity = 2; // 玩家用户UnitEntity 脏数据
}

message B2C_PlayerUploadDirtyElemData // IClientResponse
{
    int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}


// 5.玩家准备好进入战斗
message C2B_PlayeBattleReday // IClientRequest
{
    int32 RpcId = 1;
}

message B2C_PlayeBattleReday // IClientResponse
{
    int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}
