//// 战斗世界通用数据结构
message BattleWorld
{
    uint32 frame = 1;   // 世界帧
    // TODO 世界的其他配置 天空盒 场景 等战场常规信息
}

message BattleUnitEntity
{
    int64 insId = 1;                              // Unit 实例id
    map<ushort, bytes> UnitEntityElemDatas = 2;   // 实体组件数据
}

// 脏数据变动
message DirtyUnitEntity
{
    int64 insId = 1;                              // 实例id
    repeated DirtyUnitElemData eleDatas = 2;      // 组件数据集合
}

message DirtyUnitElemData
{
    ushort compId = 1;                  // 组件id
    bytes elemDatas = 2;                // element数据
}