
////>>>>>>>>>>>>>>>>>> 常规信息 
message UnitEntityCommonData // IUnitEntityElemData
{
    UnitEntityTypeEnum UnitEntityType = 1;
    map<string, string> Datas = 2;
}


message UnitEntityPosition // IUnitEntityElemData
{
    Unity.Mathematics.float2 Position = 1;
    Unity.Mathematics.float3 Forward = 2;
}


// 常规信息
message UnitEntityInfo // IUnitEntityElemData
{
    UnitEntityTypeEnum UnitEntityTypeEnum = 1;      // 实体类型
    int32 ConfigId = 2;                             // 配置ID
    int32 Speed = 3;           // 移动速度
}

////>>>>>>>>>>>>>>>>>>

//// 玩家
// 玩家信息
message UnitEntityPlayerInfo // IUnitEntityElemData
{
    int64 PlayerId = 1;        // 玩家ID
    bool IsOnline = 2;         // 是否在线
    int64 LastLoginTime = 3;   // 上次登录时间
}

// 玩家帧信息
message UnitEntityPlayerFrame // IUnitEntityElemData
{
    uint32 Frame = 1;          // 当前玩家的帧率
}

// 玩家操作
message UnitEntityPlayerOperationAction // IUnitEntityElemData
{
    short MoveAngle = 1;       // 操作角度
}


//// 地块
// 地图信息
message UnitEntityMapMessage // IUnitEntityElemData
{
    repeated bool MapData = 1;          // 地图数据
    int32 MapWidth = 2;                 // 地图宽 
    int32 MapHeight = 3;                // 地图高
    int32 UnitCellSize = 4;             // 单位Cell的长度
}


// 地块信息
message PlaneCellInfo // IUnitEntityElemData
{
    Unity.Mathematics.float2 Center = 1;            // 中心点
    repeated Unity.Mathematics.float4 PlantEdges = 2;      // 地图边
    repeated Unity.Mathematics.float2 NearPlantCells = 3;  // 邻近的地块
    float MinX = 4;                                        // 地块最小的X
    float MinY = 5;                                        // 地块最小的Y
    float MaxX = 6;                                        // 地块最大的X
    float MaxY = 7;                                        // 地块最大的Y
    int32 MapWidth 

}



