//// UnitEntityElemData 数据定义
enum UnitEntityTypeEnum
{
    Player = 1;         // 玩家
    Monster = 2;        // 怪物
}

// 常规信息
message UnitEntityInfo // IUnitEntityElemData
{
    UnitEntityTypeEnum UnitEntityTypeEnum = 1;      // 实体类型
    int32 ConfigId = 2;                             // 配置ID
}


// 玩家信息
message UnitEntityPlayerInfo // IUnitEntityElemData
{
    int64 PlayerId = 1;        // 玩家ID
    bool IsOnline = 2;         // 是否在线
    int64 LastLoginTime = 3;   // 上次登录时间
}

// 玩家帧信息
message UnitEntityPlayerFrame // IUnitEntityElemData
{
    uint32 Frame = 1;          // 当前玩家的帧率
}