
////>>>>>>>>>>>>>>>>>> 常规信息 
message UnitEntityCommonData // IUnitEntityElemData
{
    UETypeEnum UnitEntityType = 1;
    UEShowTypeEnum UEShowTypeEnum = 2;
    map<string, string> Datas = 3;
}


message UnitEntityPosition // IUnitEntityElemData
{
    Unity.Mathematics.float2 Position = 1;  // 位置
}


// 常规信息
message UnitEntityInfo // IUnitEntityElemData
{
    int32 ConfigId = 1;        // 配置ID
    int32 Speed = 2;           // 移动速度
}

// 朝向角度
message UnitEntityTowardAngle // IUnitEntityElemData
{
    short TowardAngle = 1;                  // 朝向 -180-180
}