//// 地块
// 地图信息
message UnitEntityMapMessage // IUnitEntityElemData
{
    int32 AreaSize = 1;                                     // 边宽度
    PlantInfo PlantInfo = 2;                                // 地块信息
}

message PlantInfo
{
    repeated CellInfo CellInfos = 2;                         // 网格
}


message CellInfo
{
    Unity.Mathematics.float2 CenterPoint = 1;
    repeated Unity.Mathematics.float4 Borders = 2;          // 边
}


// 地块辅助线信息
message GizmosPlantInfo // IUnitEntityElemData
{
    repeated Unity.Mathematics.float2 CenterPoints = 1;     // 点
    repeated Unity.Mathematics.float4 Borders = 2;          // 边
    int32 AreaSize = 3;                                     // 边宽度
}

// 玩家AOI辅助线
message GizmosPlayerAOICell // IUnitEntityElemData
{
    repeated int64 CellIds = 1;                             // Cell Ids
}