//// 玩家
// 玩家信息
message UnitEntityPlayerInfo // IUnitEntityElemData
{
    int64 PlayerId = 1;        // 玩家ID
    bool IsOnline = 2;         // 是否在线
    int64 LastLoginTime = 3;   // 上次登录时间
}

// 玩家数据
message UnitEntityCameraData // IUnitEntityElemData
{
    short CameraAngleOffSet = 1;            // 相机偏移角度
}


//// 地块
// 地图信息
message UnitEntityMapMessage // IUnitEntityElemData
{
    int32 AreaSize = 1;                                     // 边宽度
    PlantInfo PlantInfo = 2;                                // 地块信息
}

message PlantInfo
{
    repeated CellInfo CellInfos = 2;                         // 网格
}


message CellInfo
{
    Unity.Mathematics.float2 CenterPoint = 1;
    repeated Unity.Mathematics.float4 Borders = 2;          // 边
}


// 地块辅助线信息
message GizmosPlantInfo // IUnitEntityElemData
{
    repeated Unity.Mathematics.float2 CenterPoints = 1;     // 点
    repeated Unity.Mathematics.float4 Borders = 2;          // 边
    int32 AreaSize = 3;                                     // 边宽度
}

// 玩家AOI辅助线
message GizmosPlayerAOICell // IUnitEntityElemData
{
    repeated int64 CellIds = 1;                             // Cell Ids
}