// ============================= 数据同步 =============================
// 客户端服务器通用同步
message SyncDataUnitStruct
{
    uint32 Frame = 1;                                  // 编号
    repeated DataUnitBytes DataUnitBytes = 2;       // 数据单元
}

// 数据单元
message DataUnitBytes
{
    uint32 UnitId = 1;               // 单位uintId
    bytes UnitBytes = 2;            // 单位数据
}


// 获得所有的 DataUnit 数据
// ResponseType G2_GetAllDataUnits
message C2G_GetAllDataUnits // IClientRequest
{
    int32 RpcId = 1;
}

message G2_GetAllDataUnits // IClientResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;

    SyncDataUnitStruct UnitStructData = 1;  // 数据
}

message L2C_SyncDirtyDataUnits // IMessage
{
    SyncDataUnitStruct UnitStructData = 1;  // 数据
}


// ============================= 数据 =============================
//// 玩家 角色信息
message RoleInfoUnitData // IUnitData
{
    string NickName = 1;    // 昵称
}