
//// 客户端Main向网络线程发送消息
// ResponseType NetLobby2MainLogin
message Main2NetLobbyLogin // IRequest
{
	int32 RpcId = 1;
	int32 OwnerFiberId = 2;
	string Account = 3;		// 账号
	string Password = 4; 	// 密码
}

message NetLobby2MainLogin // IResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;

	int64 PlayerId = 4;
}

// 登录账号服务器
// ResponseType A2C_Login
message C2A_Login // ISessionRequest
{
	int32 RpcId = 1;
	string  Account = 2;  // 帐号
	string  Password = 3;  // 密码
}

message A2C_Login // ISessionResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;

	string Address = 4;				// 大厅地址
	string Token = 5;				// Token
}

// 登录大厅服务器
// ResponseType L2C_LoginLobby
message C2L_LoginLobby // ISessionRequest
{
	int32 RpcId = 1;
	
	string Token = 2;				// Token
}

message L2C_LoginLobby // ISessionResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
	int64 PlayerId = 4;
}


