syntax = "proto3";
package ET;
// 战斗通讯实体


enum UnitEntityTypeEnum
{
    Player = 1;         // 玩家
    Monster = 2;        // 怪物
}

// 常规信息
message UnitEntityInfo // IUnitEntityElemData
{
    UnitEntityTypeEnum unitEntityTypeEnum = 1;      // 实体类型
    int32 ConfigId = 2;                             // 配置ID
}


// 玩家信息
message UnitEntityPlayerInfo // IUnitEntityElemData
{
    int64 playerId = 1;     // 玩家ID
}

// 未登录的常规协议

//// 网络
// ResponseType G2C_Ping
message C2G_Ping // ISessionRequest
{
	int32 RpcId = 1;
}

message G2C_Ping // ISessionResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
	int64 Time = 4;
}

// ResponseType G2C_Benchmark
message C2G_Benchmark // ISessionRequest
{
	int32 RpcId = 1;
}

message G2C_Benchmark // ISessionResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}

// ResponseType NetClient2Main_Login
message Main2NetClient_Login // IRequest
{
	int32 RpcId = 1;
	int32 OwnerFiberId = 2;
	string Account = 3;		// 账号
	string Password = 4; 	// 密码
}

message NetClient2Main_Login // IResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;

	int64 PlayerId = 4;
}

// 登录账号服务器
// ResponseType A2C_Login
message C2A_Login // ISessionRequest
{
	int32 RpcId = 1;
	string  Account = 2;  // 帐号
	string  Password = 3;  // 密码
}

message A2C_Login // ISessionResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;

	string Address = 4;				// 大厅地址
	string Token = 5;				// Token
}

// 登录大厅服务器
// ResponseType L2C_LoginLobby
message C2L_LoginLobby // ISessionRequest
{
	int32 RpcId = 1;
	
	string Token = 2;				// Token
}

message L2C_LoginLobby // ISessionResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
	int64 PlayerId = 4;
}




// ResponseType L2C_StartMatchBattle
// 1.开始匹配战斗
message C2L_StartMatchBattle // IClientRequest
{
	int32 RpcId = 1;
	// TODO 各个战斗服的ping值
}

message L2C_StartMatchBattle // IClientResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}


// 2.通知匹配成功
message L2C_MatchBattleSuccess // IMessage
{
	// 匹配的服务器 Node
	// TODO 服务器 Node
	string Token = 1;	// 加入玩家的签名
}


// 3.玩家进入战斗
message C2B_PlayerEnterBattle // ISessionRequest
{
	int32 RpcId = 1;
	string Token = 2;
}

message B2C_PlayerEnterBattle // ISessionResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}



// 链接服务器主动断开 (不要重连)
message G2C_SessionDisconnect // IMessage
{
    int32 Error = 1;    // 断开原因
}


message HttpGetRouterResponse
{
	repeated string Routers = 1;
	repeated string Accounts = 2;
}


// 玩家与大厅间的数据同步接口
// ============================= 数据结构 =============================
// 客户端服务器通用同步
message SyncDataUnitStruct
{
    uint32 Frame = 1;                                  // 编号
    repeated DataUnitBytes DataUnitBytes = 2;       // 数据单元
}

// 数据单元
message DataUnitBytes
{
    uint32 UnitId = 1;               // 单位uintId
    bytes UnitBytes = 2;            // 单位数据
}



// ============================= 协议 =============================
//// 数据同步
// 获得所有的 DataUnit 数据
// ResponseType G2_GetAllDataUnits
message C2G_GetAllDataUnits // IClientRequest
{
    int32 RpcId = 1;
}

message G2_GetAllDataUnits // IClientResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;

    SyncDataUnitStruct UnitStructData = 1;  // 数据
}

message L2C_SyncDirtyDataUnits // IMessage
{
    SyncDataUnitStruct UnitStructData = 1;  // 数据
}



// ============================= 数据 =============================
//// 玩家 角色信息
message RoleInfoUnitData // IUnitData
{
    string NickName = 1;    // 昵称
}

