syntax = "proto3";
package ET;
enum WorldStatusEnum
{
    WS_Init = 0;                                  // 初始化状态
    WS_Battle = 1;                                // 战斗状态
    WS_Finish = 2;                                // 战斗结束状态
}


//// 战斗世界通用数据结构
message BattleWorld
{
    uint32 Frame = 1;                           // 世界帧
    WorldStatusEnum WorldStatus = 2;            // 世界状态
    // TODO 世界的其他配置 天空盒 场景 等战场常规信息
}

message BattleUnitEntity
{
    int64 InsId = 1;                              // Unit 实例id
    map<ushort, bytes> UnitEntityElemDatas = 2;   // 实体组件数据
}

// 脏数据变动
message DirtyUnitEntity
{
    int64 InsId = 1;                              // 实例id
    repeated DirtyUnitElemData EleDatas = 2;      // 组件数据集合
}

message DirtyUnitElemData
{
    ushort CompId = 1;                  // 组件id
    bytes ElemDatas = 2;                // element数据
}


//// 常规信息 
message UnitEntityCommonData // IUnitEntityElemData
{
    UnitEntityTypeEnum UnitEntityType = 1;
    map<string, string> Datas = 2;
}


message UnitEntityPosition // IUnitEntityElemData
{
    Unity.Mathematics.int3 Position = 1;
    Unity.Mathematics.int3 Forward = 2;
}




// 常规信息
message UnitEntityInfo // IUnitEntityElemData
{
    UnitEntityTypeEnum UnitEntityTypeEnum = 1;      // 实体类型
    int32 ConfigId = 2;                             // 配置ID
}


// 玩家信息
message UnitEntityPlayerInfo // IUnitEntityElemData
{
    int64 PlayerId = 1;        // 玩家ID
    bool IsOnline = 2;         // 是否在线
    int64 LastLoginTime = 3;   // 上次登录时间
}

// 玩家帧信息
message UnitEntityPlayerFrame // IUnitEntityElemData
{
    uint32 Frame = 1;          // 当前玩家的帧率
}



//// 通讯协议

// 1.获得玩家的视野世界信息
// ResponseType B2C_PlayerGetAllAOIWorldData
message C2B_PlayerGetAllAOIWorldData // IClientRequest
{
    int32 RpcId = 1;
}

message B2C_PlayerGetAllAOIWorldData // IClientResponse
{
    int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;

    BattleWorld BattleWorld = 4;
    repeated BattleUnitEntity BattleUnitEntity = 5;
    BattleUnitEntity MyPlayerUnitEntity = 6;
}

// 2.战斗场景玩家心跳
// ResponseType B2C_PlayerBattleWorldPing
message C2B_PlayerBattleWorldPing // IClientRequest
{
    int32 RpcId = 1;
    int64 ClientTime = 2;
}

message B2C_PlayerBattleWorldPing // IClientResponse
{
    int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
    int64 SendClientTime = 4;
    uint32 PlayerCurFrame = 4;         // 当前战斗世界的帧号
}

// 3.玩家战斗脏数据推送
message L2C_PlayerAOIWorldDirtyPush // IMessage
{
    uint32 startFrame = 1;                          // 开始帧数
    uint32 endFrame = 2;                            // 解锁帧数
    repeated DirtyUnitEntity DirtyUnitEntities = 3; // 脏数据
}

//// 客户端Main向网络线程发送消息
// ResponseType NetBattle2MainLogin
message Main2NetBattleLogin // IRequest
{
	int32 RpcId = 1;
	int32 OwnerFiberId = 2;
	string RouterAddress = 3;				// 路由地址
	string Address = 3;						// 地址
	string Token = 4;						// Token 令牌	
}

message NetBattle2MainLogin // IResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}


// 3.玩家进入战斗 对Session 进行登录验证
// ResponseType B2C_Login
message C2B_Login // ISessionRequest
{
	int32 RpcId = 1;
	string Token = 2;
}

message B2C_Login // ISessionResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}

// 4.玩家通知准备完成
// ResponseType B2C_PlayerReadyCompleted
message C2B_PlayerReadyCompleted
{
	int32 RpcId = 1;
}

message B2C_PlayerReadyCompleted
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}

// 未登录的常规协议

//// 网络
// ResponseType G2C_Ping
message C2G_Ping // ISessionRequest
{
	int32 RpcId = 1;
}

message G2C_Ping // ISessionResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
	int64 Time = 4;
}

// ResponseType G2C_Benchmark
message C2G_Benchmark // ISessionRequest
{
	int32 RpcId = 1;
}

message G2C_Benchmark // ISessionResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}


//// 客户端Main向Lobby网络线程发送消息
// ResponseType NetLobby2MainLogin
message Main2NetLobbyLogin // IRequest
{
	int32 RpcId = 1;
	int32 OwnerFiberId = 2;
	string Account = 3;		// 账号
	string Password = 4; 	// 密码
}

message NetLobby2MainLogin // IResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;

	int64 PlayerId = 4;
}

// 登录账号服务器
// ResponseType A2C_Login
message C2A_Login // ISessionRequest
{
	int32 RpcId = 1;
	string  Account = 2;  // 帐号
	string  Password = 3;  // 密码
}

message A2C_Login // ISessionResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;

	string Address = 4;				// 大厅地址
	string Token = 5;				// Token
}

// 登录大厅服务器
// ResponseType L2C_LoginLobby
message C2L_LoginLobby // ISessionRequest
{
	int32 RpcId = 1;
	
	string Token = 2;				// Token
}

message L2C_LoginLobby // ISessionResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
	int64 PlayerId = 4;
}




// 链接服务器主动断开 (不要重连)
message G2C_SessionDisconnect // IMessage
{
    int32 Error = 1;    // 断开原因
}


message HttpGetRouterResponse
{
	repeated string Routers = 1;
	repeated string Accounts = 2;
}


// 玩家与大厅间的数据同步接口
// ============================= 数据结构 =============================
// 客户端服务器通用同步
message SyncDataUnitStruct
{
    uint32 Frame = 1;                                  // 编号
    repeated DataUnitBytes DataUnitBytes = 2;       // 数据单元
}

// 数据单元
message DataUnitBytes
{
    uint32 UnitId = 1;               // 单位uintId
    bytes UnitBytes = 2;            // 单位数据
}



// ============================= 协议 =============================
//// 数据同步
// 获得所有的 DataUnit 数据
// ResponseType L2C_GetAllDataUnits
message C2L_GetAllDataUnits // IClientRequest
{
    int32 RpcId = 1;
}

message L2C_GetAllDataUnits // IClientResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;

    SyncDataUnitStruct UnitStructData = 1;  // 数据
}

message L2C_SyncDirtyDataUnits // IMessage
{
    SyncDataUnitStruct UnitStructData = 1;  // 数据
}



// ============================= 数据 =============================
//// 玩家 角色信息
message RoleInfoUnitData // IUnitData
{
    string NickName = 1;    // 昵称
}

//// 战斗流程

// 1.开始匹配战斗
// ResponseType L2C_StartMatchBattle
message C2L_StartMatchBattle // IClientRequest
{
	int32 RpcId = 1;
	// TODO 各个战斗服的ping值
}

message L2C_StartMatchBattle // IClientResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}


// 2.通知匹配成功
message L2C_MatchBattleSuccess // IMessage
{
	string RouterAddress = 1;	// 路由地址
	string BattleAddress = 2;	// 战斗服地址
	string Token = 3;			// Token
}

